<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','SiteController@home');

Route::get('/login','Authcontroller@login')->name('login');
Route::post('/postlogin','Authcontroller@postlogin');
Route::get('/logout','Authcontroller@logout');

Route::group(['middleware'=>'auth'],function(){
	Route::get('/dashboard','dashboardcontroller@index');
	Route::resource('/report', 'reportcontroller');
	Route::get('/report','reportcontroller@index');
	Route::POST('/report/create','reportcontroller@create');
	Route::get('/report/{id}/edit','reportcontroller@edit');
	Route::POST('/report/{id}/update','reportcontroller@update');
	Route::get('/report/{id}/delete','reportcontroller@delete');
	Route::get('/print-report','reportcontroller@export');
	Route::resource('/insreport', 'insreportcontroller');
	Route::get('/insreport','insreportcontroller@index');
	Route::POST('/insreport/create','insreportcontroller@create');
	Route::get('/insreport/{id}/edit','insreportcontroller@edit');
	Route::POST('/insreport/{id}/update','insreportcontroller@update');
	Route::get('/insreport/{id}/delete','insreportcontroller@delete');
	Route::get('/print-insreport','insreportcontroller@export');
	Route::resource('/evaluation', 'evaluationcontroller');
	Route::get('/evaluation','evaluationcontroller@index');
	Route::POST('/evaluation/create','evaluationcontroller@create');
	Route::get('/evaluation/{id}/edit','evaluationcontroller@edit');
	Route::POST('/evaluation/{id}/update','evaluationcontroller@update');
	Route::get('/evaluation/{id}/delete','evaluationcontroller@delete');
	Route::get('/print-evaluation','evaluationcontroller@export');
	Route::resource('/weekly', 'weeklycontroller');
	Route::get('/weekly','weeklycontroller@index');
	Route::POST('/weekly/create','weeklycontroller@create');
	Route::get('/weekly/{id}/edit','weeklycontroller@edit');
	Route::POST('/weekly/{id}/update','weeklycontroller@update');
	Route::get('/weekly/{id}/delete','weeklycontroller@delete');
	Route::get('/print','weeklycontroller@export');
	Route::resource('/juklak', 'juklakcontroller');
	Route::get('/juklak','juklakcontroller@index');
	Route::POST('/juklak/create','juklakcontroller@create');
	Route::get('/juklak/{id}/edit','juklakcontroller@edit');
	Route::POST('/juklak/{id}/update','juklakcontroller@update');
	Route::get('/juklak/{id}/delete','juklakcontroller@delete');
	Route::get('/print-juklak','juklakcontroller@export');
	Route::resource('/gugus', 'guguscontroller');
	Route::get('/gugus','guguscontroller@index');
	Route::POST('/gugus/create','guguscontroller@create');
	Route::get('/gugus/{id}/edit','guguscontroller@edit');
	Route::POST('/gugus/{id}/update','guguscontroller@update');
	Route::get('/gugus/{id}/delete','guguscontroller@delete');
	Route::get('/print-gugus','guguscontroller@export');
	Route::resource('/perizinan', 'perizinancontroller');
	Route::get('/perizinan','perizinancontroller@index');
	Route::POST('/perizinan/create','perizinancontroller@create');
	Route::get('/perizinan/{id}/edit','perizinancontroller@edit');
	Route::POST('/perizinan/{id}/update','perizinancontroller@update');
	Route::get('/perizinan/{id}/delete','perizinancontroller@delete');
	Route::get('/print-perizinan','perizinancontroller@export');
	Route::resource('/smasuk', 'smasukcontroller');
	Route::get('/smasuk','smasukcontroller@index');
	Route::POST('/smasuk/create','smasukcontroller@create');
	Route::get('/smasuk/{id}/edit','smasukcontroller@edit');
	Route::POST('/smasuk/{id}/update','smasukcontroller@update');
	Route::get('/smasuk/{id}/delete','smasukcontroller@delete');
	Route::get('/print-smasuk','smasukcontroller@export');
	Route::resource('/skeluar', 'skeluarcontroller');
	Route::get('/skeluar','skeluarcontroller@index');
	Route::POST('/skeluar/create','skeluarcontroller@create');
	Route::get('/skeluar/{id}/edit','skeluarcontroller@edit');
	Route::POST('/skeluar/{id}/update','skeluarcontroller@update');
	Route::get('/skeluar/{id}/delete','skeluarcontroller@delete');
	Route::get('/print-skeluar','skeluarcontroller@export');
	Route::resource('/qc', 'qccontroller');
	Route::get('/qc','qccontroller@index');
	Route::POST('/qc/create','qccontroller@create');
	Route::get('/qc/{id}/edit','qccontroller@edit');
	Route::POST('/qc/{id}/update','qccontroller@update');
	Route::get('/qc/{id}/delete','qccontroller@delete');
	Route::get('/print-qc','qccontroller@export');
	Route::resource('/qc2', 'qc2controller');
	Route::get('/qc2','qc2controller@index');
	Route::POST('/qc2/create','qc2controller@create');
	Route::get('/qc2/{id}/edit','qc2controller@edit');
	Route::POST('/qc2/{id}/update','qc2controller@update');
	Route::get('/qc2/{id}/delete','qc2controller@delete');
	Route::get('/print-qc2','qc2controller@export');
	Route::resource('/logbook', 'logbookcontroller');
	Route::get('/logbook','logbookcontroller@index');
	Route::resource('/ammonia1b', 'ammonia1bcontroller');
	Route::get('/ammonia1b','ammonia1bcontroller@index');
	Route::POST('/ammonia1b/create','ammonia1bcontroller@create');
	Route::get('/ammonia1b/{id}/edit','ammonia1bcontroller@edit');
	Route::POST('/ammonia1b/{id}/update','ammonia1bcontroller@update');
	Route::get('/ammonia1b/{id}/delete','ammonia1bcontroller@delete');
	Route::get('/ammonia1b/{id}/detail','ammonia1bcontroller@detail');
	Route::resource('/urea1b', 'urea1bcontroller');
	Route::get('/urea1b','urea1bcontroller@index');
	Route::POST('/urea1b/create','urea1bcontroller@create');
	Route::get('/urea1b/{id}/edit','urea1bcontroller@edit');
	Route::POST('/urea1b/{id}/update','urea1bcontroller@update');
	Route::get('/urea1b/{id}/delete','urea1bcontroller@delete');
	Route::get('/urea1b/{id}/detail','urea1bcontroller@detail');
	Route::resource('/utilitas1b', 'utilitas1bcontroller');
	Route::get('/utilitas1b','utilitas1bcontroller@index');
	Route::POST('/utilitas1b/create','utilitas1bcontroller@create');
	Route::get('/utilitas1b/{id}/edit','utilitas1bcontroller@edit');
	Route::POST('/utilitas1b/{id}/update','utilitas1bcontroller@update');
	Route::get('/utilitas1b/{id}/delete','utilitas1bcontroller@delete');
	Route::get('/utilitas1b/{id}/detail','utilitas1bcontroller@detail');
	Route::resource('/ammonia2b', 'ammonia2bcontroller');
	Route::get('/ammonia2b','ammonia2bcontroller@index');
	Route::POST('/ammonia2b/create','ammonia2bcontroller@create');
	Route::get('/ammonia2b/{id}/edit','ammonia2bcontroller@edit');
	Route::POST('/ammonia2b/{id}/update','ammonia2bcontroller@update');
	Route::get('/ammonia2b/{id}/delete','ammonia2bcontroller@delete');
	Route::get('/ammonia2b/{id}/detail','ammonia2bcontroller@detail');
	Route::resource('/urea2b', 'urea2bcontroller');
	Route::get('/urea2b','urea2bcontroller@index');
	Route::POST('/urea2b/create','urea2bcontroller@create');
	Route::get('/urea2b/{id}/edit','urea2bcontroller@edit');
	Route::POST('/urea2b/{id}/update','urea2bcontroller@update');
	Route::get('/urea2b/{id}/delete','urea2bcontroller@delete');
	Route::get('/urea2b/{id}/detail','urea2bcontroller@detail');
	Route::resource('/utilitas2b', 'utilitas2bcontroller');
	Route::get('/utilitas2b','utilitas2bcontroller@index');
	Route::POST('/utilitas2b/create','utilitas2bcontroller@create');
	Route::get('/utilitas2b/{id}/edit','utilitas2bcontroller@edit');
	Route::POST('/utilitas2b/{id}/update','utilitas2bcontroller@update');
	Route::get('/utilitas2b/{id}/delete','utilitas2bcontroller@delete');
	Route::get('/utilitas2b/{id}/detail','utilitas2bcontroller@detail');
	Route::resource('/ammonia3', 'ammonia3controller');
	Route::get('/ammonia3','ammonia3controller@index');
	Route::POST('/ammonia3/create','ammonia3controller@create');
	Route::get('/ammonia3/{id}/edit','ammonia3controller@edit');
	Route::POST('/ammonia3/{id}/update','ammonia3controller@update');
	Route::get('/ammonia3/{id}/delete','ammonia3controller@delete');
	Route::get('/ammonia3/{id}/detail','ammonia3controller@detail');
	Route::resource('/urea3', 'urea3controller');
	Route::get('/urea3','urea3controller@index');
	Route::POST('/urea3/create','urea3controller@create');
	Route::get('/urea3/{id}/edit','urea3controller@edit');
	Route::POST('/urea3/{id}/update','urea3controller@update');
	Route::get('/urea3/{id}/delete','urea3controller@delete');
	Route::get('/urea3/{id}/detail','urea3controller@detail');
	Route::resource('/utilitas3', 'utilitas3controller');
	Route::get('/utilitas3','utilitas3controller@index');
	Route::POST('/utilitas3/create','utilitas3controller@create');
	Route::get('/utilitas3/{id}/edit','utilitas3controller@edit');
	Route::POST('/utilitas3/{id}/update','utilitas3controller@update');
	Route::get('/utilitas3/{id}/delete','utilitas3controller@delete');
	Route::get('/utilitas3/{id}/detail','utilitas3controller@detail');
	Route::resource('/ammonia4', 'ammonia4controller');
	Route::get('/ammonia4','ammonia4controller@index');
	Route::POST('/ammonia4/create','ammonia4controller@create');
	Route::get('/ammonia4/{id}/edit','ammonia4controller@edit');
	Route::POST('/ammonia4/{id}/update','ammonia4controller@update');
	Route::get('/ammonia4/{id}/delete','ammonia4controller@delete');
	Route::get('/ammonia4/{id}/detail','ammonia4controller@detail');
	Route::resource('/urea4', 'urea4controller');
	Route::get('/urea4','urea4controller@index');
	Route::POST('/urea4/create','urea4controller@create');
	Route::get('/urea4/{id}/edit','urea4controller@edit');
	Route::POST('/urea4/{id}/update','urea4controller@update');
	Route::get('/urea4/{id}/delete','urea4controller@delete');
	Route::get('/urea4/{id}/detail','urea4controller@detail');
	Route::resource('/utilitas4', 'utilitas4controller');
	Route::get('/utilitas4','utilitas4controller@index');
	Route::POST('/utilitas4/create','utilitas4controller@create');
	Route::get('/utilitas4/{id}/edit','utilitas4controller@edit');
	Route::POST('/utilitas4/{id}/update','utilitas4controller@update');
	Route::get('/utilitas4/{id}/delete','utilitas4controller@delete');
	Route::get('/utilitas4/{id}/detail','utilitas4controller@detail');
	Route::resource('/npk', 'npkcontroller');
	Route::get('/npk','npkcontroller@index');
	Route::POST('/npk/create','npkcontroller@create');
	Route::get('/npk/{id}/edit','npkcontroller@edit');
	Route::POST('/npk/{id}/update','npkcontroller@update');
	Route::get('/npk/{id}/delete','npkcontroller@delete');
	Route::get('/npk/{id}/detail','npkcontroller@detail');
	Route::resource('/stgbbjetty', 'stgbbjettycontroller');
	Route::get('/stgbbjetty','stgbbjettycontroller@index');
	Route::POST('/stgbbjetty/create','stgbbjettycontroller@create');
	Route::get('/stgbbjetty/{id}/edit','stgbbjettycontroller@edit');
	Route::POST('/stgbbjetty/{id}/update','stgbbjettycontroller@update');
	Route::get('/stgbbjetty/{id}/delete','stgbbjettycontroller@delete');
	Route::get('/stgbbjetty/{id}/detail','stgbbjettycontroller@detail');

	Route::resource('/rbiammonia1b', 'rbiammonia1bcontroller');
	Route::get('/rbiammonia1b','rbiammonia1bcontroller@index');
	Route::POST('/rbiammonia1b/create','rbiammonia1bcontroller@create');
	Route::get('/rbiammonia1b/{id}/edit','rbiammonia1bcontroller@edit');
	Route::POST('/rbiammonia1b/{id}/update','rbiammonia1bcontroller@update');
	Route::get('/rbiammonia1b/{id}/delete','rbiammonia1bcontroller@delete');
	Route::get('/rbiammonia1b/{id}/detail','rbiammonia1bcontroller@detail');
	Route::get('/prd_ammonia1b','rbiammonia1bcontroller@index1');
	Route::get('/he_ammonia1b','rbiammonia1bcontroller@index2');
	Route::get('/pv_ammonia1b','rbiammonia1bcontroller@index3');

	Route::resource('/rbiammonia1bpv', 'rbiammonia1bpvcontroller');
	Route::POST('/rbiammonia1bpv/create','rbiammonia1bpvcontroller@create');
	Route::get('/rbiammonia1bpv/{id}/edit','rbiammonia1bpvcontroller@edit');
	Route::POST('/rbiammonia1bpv/{id}/update','rbiammonia1bpvcontroller@update');
	Route::get('/rbiammonia1bpv/{id}/delete','rbiammonia1bpvcontroller@delete');
	Route::get('/rbiammonia1bpv/{id}/detail','rbiammonia1bpvcontroller@detail');

	Route::resource('/rbiammonia1bhe', 'rbiammonia1bhecontroller');
	Route::POST('/rbiammonia1bhe/create','rbiammonia1bhecontroller@create');
	Route::get('/rbiammonia1bhe/{id}/edit','rbiammonia1bhecontroller@edit');
	Route::POST('/rbiammonia1bhe/{id}/update','rbiammonia1bhecontroller@update');
	Route::get('/rbiammonia1bhe/{id}/delete','rbiammonia1bhecontroller@delete');
	Route::get('/rbiammonia1bhe/{id}/detail','rbiammonia1bhecontroller@detail');

	Route::resource('/rbiurea1b', 'rbiurea1bcontroller');
	Route::get('/rbiurea1b','rbiurea1bcontroller@index');
	Route::POST('/rbiurea1b/create','rbiurea1bcontroller@create');
	Route::get('/rbiurea1b/{id}/edit','rbiurea1bcontroller@edit');
	Route::POST('/rbiurea1b/{id}/update','rbiurea1bcontroller@update');
	Route::get('/rbiurea1b/{id}/delete','rbiurea1bcontroller@delete');
	Route::get('/rbiurea1b/{id}/detail','rbiurea1bcontroller@detail');
	Route::get('/prd_urea1b','rbiurea1bcontroller@index1');
	Route::get('/pv_urea1b','rbiurea1bcontroller@index2');
	Route::get('/ast_urea1b','rbiurea1bcontroller@index3');
	Route::get('/he_urea1b','rbiurea1bcontroller@index4');

	Route::resource('/rbiurea1bpv', 'rbiurea1bpvcontroller');
	Route::POST('/rbiurea1bpv/create','rbiurea1bpvcontroller@create');
	Route::get('/rbiurea1bpv/{id}/edit','rbiurea1bpvcontroller@edit');
	Route::POST('/rbiurea1bpv/{id}/update','rbiurea1bpvcontroller@update');
	Route::get('/rbiurea1bpv/{id}/delete','rbiurea1bpvcontroller@delete');
	Route::get('/rbiurea1bpv/{id}/detail','rbiurea1bpvcontroller@detail');

	Route::resource('/rbiurea1btank', 'rbiurea1btankcontroller');
	Route::POST('/rbiurea1btank/create','rbiurea1btankcontroller@create');
	Route::get('/rbiurea1btank/{id}/edit','rbiurea1btankcontroller@edit');
	Route::POST('/rbiurea1btank/{id}/update','rbiurea1btankcontroller@update');
	Route::get('/rbiurea1btank/{id}/delete','rbiurea1btankcontroller@delete');
	Route::get('/rbiurea1btank/{id}/detail','rbiurea1btankcontroller@detail');

	Route::resource('/rbiurea1bhe', 'rbiurea1bhecontroller');
	Route::POST('/rbiurea1bhe/create','rbiurea1bhecontroller@create');
	Route::get('/rbiurea1bhe/{id}/edit','rbiurea1bhecontroller@edit');
	Route::POST('/rbiurea1bhe/{id}/update','rbiurea1bhecontroller@update');
	Route::get('/rbiurea1bhe/{id}/delete','rbiurea1bhecontroller@delete');
	Route::get('/rbiurea1bhe/{id}/detail','rbiurea1bhecontroller@detail');

	Route::resource('/rbiutilitas1b', 'rbiutilitas1bcontroller');
	Route::get('/rbiutilitas1b','rbiutilitas1bcontroller@index');
	Route::POST('/rbiutilitas1b/create','rbiutilitas1bcontroller@create');
	Route::get('/rbiutilitas1b/{id}/edit','rbiutilitas1bcontroller@edit');
	Route::POST('/rbiutilitas1b/{id}/update','rbiutilitas1bcontroller@update');
	Route::get('/rbiutilitas1b/{id}/delete','rbiutilitas1bcontroller@delete');
	Route::get('/rbiutilitas1b/{id}/detail','rbiutilitas1bcontroller@detail');
	Route::get('/pv_utilitas1b','rbiutilitas1bcontroller@index1');
	Route::get('/ast_utilitas1b','rbiutilitas1bcontroller@index2');
	Route::get('/he_utilitas1b','rbiutilitas1bcontroller@index3');

	Route::resource('/rbiutilitas1btank', 'rbiutilitas1btankcontroller');
	Route::POST('/rbiutilitas1btank/create','rbiutilitas1btankcontroller@create');
	Route::get('/rbiutilitas1btank/{id}/edit','rbiutilitas1btankcontroller@edit');
	Route::POST('/rbiutilitas1btank/{id}/update','rbiutilitas1btankcontroller@update');
	Route::get('/rbiutilitas1btank/{id}/delete','rbiutilitas1btankcontroller@delete');
	Route::get('/rbiutilitas1btank/{id}/detail','rbiutilitas1btankcontroller@detail');

	Route::resource('/rbiutilitas1bhe', 'rbiutilitas1bhecontroller');
	Route::POST('/rbiutilitas1bhe/create','rbiutilitas1bhecontroller@create');
	Route::get('/rbiutilitas1bhe/{id}/edit','rbiutilitas1bhecontroller@edit');
	Route::POST('/rbiutilitas1bhe/{id}/update','rbiutilitas1bhecontroller@update');
	Route::get('/rbiutilitas1bhe/{id}/delete','rbiutilitas1bhecontroller@delete');
	Route::get('/rbiutilitas1bhe/{id}/detail','rbiutilitas1bhecontroller@detail');

	Route::resource('/rbiutilitas2b', 'rbiutilitas2bcontroller');
	Route::get('/rbiutilitas2b','rbiutilitas2bcontroller@index');
	Route::POST('/rbiutilitas2b/create','rbiutilitas2bcontroller@create');
	Route::get('/rbiutilitas2b/{id}/edit','rbiutilitas2bcontroller@edit');
	Route::POST('/rbiutilitas2b/{id}/update','rbiutilitas2bcontroller@update');
	Route::get('/rbiutilitas2b/{id}/delete','rbiutilitas2bcontroller@delete');
	Route::get('/rbiutilitas2b/{id}/detail','rbiutilitas2bcontroller@detail');
	Route::get('/pv_utilitas2b','rbiutilitas2bcontroller@index1');
	Route::get('/ast_utilitas2b','rbiutilitas2bcontroller@index2');
	Route::get('/he_utilitas2b','rbiutilitas2bcontroller@index3');

	Route::resource('/rbiutilitas2btank', 'rbiutilitas2btankcontroller');
	Route::POST('/rbiutilitas2btank/create','rbiutilitas2btankcontroller@create');
	Route::get('/rbiutilitas2btank/{id}/edit','rbiutilitas2btankcontroller@edit');
	Route::POST('/rbiutilitas2btank/{id}/update','rbiutilitas2btankcontroller@update');
	Route::get('/rbiutilitas2btank/{id}/delete','rbiutilitas2btankcontroller@delete');
	Route::get('/rbiutilitas2btank/{id}/detail','rbiutilitas2btankcontroller@detail');

	Route::resource('/rbiutilitas2bhe', 'rbiutilitas2bhecontroller');
	Route::POST('/rbiutilitas2bhe/create','rbiutilitas2bhecontroller@create');
	Route::get('/rbiutilitas2bhe/{id}/edit','rbiutilitas2bhecontroller@edit');
	Route::POST('/rbiutilitas2bhe/{id}/update','rbiutilitas2bhecontroller@update');
	Route::get('/rbiutilitas2bhe/{id}/delete','rbiutilitas2bhecontroller@delete');
	Route::get('/rbiutilitas2bhe/{id}/detail','rbiutilitas2bhecontroller@detail');

	Route::resource('/rbiammonia2b', 'rbiammonia2bcontroller');
	Route::get('/rbiammonia2b','rbiammonia2bcontroller@index');
	Route::POST('/rbiammonia2b/create','rbiammonia2bcontroller@create');
	Route::get('/rbiammonia2b/{id}/edit','rbiammonia2bcontroller@edit');
	Route::POST('/rbiammonia2b/{id}/update','rbiammonia2bcontroller@update');
	Route::get('/rbiammonia2b/{id}/delete','rbiammonia2bcontroller@delete');
	Route::get('/rbiammonia2b/{id}/detail','rbiammonia2bcontroller@detail');
	Route::get('/prd_ammonia2b','rbiammonia2bcontroller@index1');
	Route::get('/pv_ammonia2b','rbiammonia2bcontroller@index2');
	Route::get('/he_ammonia2b','rbiammonia2bcontroller@index3');

	Route::resource('/rbiammonia2bpv', 'rbiammonia2bpvcontroller');
	Route::POST('/rbiammonia2bpv/create','rbiammonia2bpvcontroller@create');
	Route::get('/rbiammonia2bpv/{id}/edit','rbiammonia2bpvcontroller@edit');
	Route::POST('/rbiammonia2bpv/{id}/update','rbiammonia2bpvcontroller@update');
	Route::get('/rbiammonia2bpv/{id}/delete','rbiammonia2bpvcontroller@delete');
	Route::get('/rbiammonia2bpv/{id}/detail','rbiammonia2bpvcontroller@detail');

	Route::resource('/rbiammonia2bhe', 'rbiammonia2bhecontroller');
	Route::POST('/rbiammonia2bhe/create','rbiammonia2bhecontroller@create');
	Route::get('/rbiammonia2bhe/{id}/edit','rbiammonia2bhecontroller@edit');
	Route::POST('/rbiammonia2bhe/{id}/update','rbiammonia2bhecontroller@update');
	Route::get('/rbiammonia2bhe/{id}/delete','rbiammonia2bhecontroller@delete');
	Route::get('/rbiammonia2bhe/{id}/detail','rbiammonia2bhecontroller@detail');

	Route::resource('/rbiurea2b', 'rbiurea2bcontroller');
	Route::get('/rbiurea2b','rbiurea2bcontroller@index');
	Route::POST('/rbiurea2b/create','rbiurea2bcontroller@create');
	Route::get('/rbiurea2b/{id}/edit','rbiurea2bcontroller@edit');
	Route::POST('/rbiurea2b/{id}/update','rbiurea2bcontroller@update');
	Route::get('/rbiurea2b/{id}/delete','rbiurea2bcontroller@delete');
	Route::get('/rbiurea2b/{id}/detail','rbiurea2bcontroller@detail');
	Route::get('/prd_urea2b','rbiurea2bcontroller@index1');
	Route::get('/pv_urea2b','rbiurea2bcontroller@index2');
	Route::get('/ast_urea2b','rbiurea2bcontroller@index3');
	Route::get('/he_urea2b','rbiurea2bcontroller@index4');

	Route::resource('/rbiurea2bpv', 'rbiurea2bpvcontroller');
	Route::POST('/rbiurea2bpv/create','rbiurea2bpvcontroller@create');
	Route::get('/rbiurea2bpv/{id}/edit','rbiurea2bpvcontroller@edit');
	Route::POST('/rbiurea2bpv/{id}/update','rbiurea2bpvcontroller@update');
	Route::get('/rbiurea2bpv/{id}/delete','rbiurea2bpvcontroller@delete');
	Route::get('/rbiurea2bpv/{id}/detail','rbiurea2bpvcontroller@detail');

	Route::resource('/rbiurea2btank', 'rbiurea2btankcontroller');
	Route::POST('/rbiurea2btank/create','rbiurea2btankcontroller@create');
	Route::get('/rbiurea2btank/{id}/edit','rbiurea2btankcontroller@edit');
	Route::POST('/rbiurea2btank/{id}/update','rbiurea2btankcontroller@update');
	Route::get('/rbiurea2btank/{id}/delete','rbiurea2btankcontroller@delete');
	Route::get('/rbiurea2btank/{id}/detail','rbiurea2btankcontroller@detail');

	Route::resource('/rbiurea2bhe', 'rbiurea2bhecontroller');
	Route::POST('/rbiurea2bhe/create','rbiurea2bhecontroller@create');
	Route::get('/rbiurea2bhe/{id}/edit','rbiurea2bhecontroller@edit');
	Route::POST('/rbiurea2bhe/{id}/update','rbiurea2bhecontroller@update');
	Route::get('/rbiurea2bhe/{id}/delete','rbiurea2bhecontroller@delete');
	Route::get('/rbiurea2bhe/{id}/detail','rbiurea2bhecontroller@detail');

	Route::resource('/rbiammonia3', 'rbiammonia3controller');
	Route::get('/rbiammonia3','rbiammonia3controller@index');
	Route::POST('/rbiammonia3/create','rbiammonia3controller@create');
	Route::get('/rbiammonia3/{id}/edit','rbiammonia3controller@edit');
	Route::POST('/rbiammonia3/{id}/update','rbiammonia3controller@update');
	Route::get('/rbiammonia3/{id}/delete','rbiammonia3controller@delete');
	Route::get('/rbiammonia3/{id}/detail','rbiammonia3controller@detail');
	Route::get('/prd_ammonia3','rbiammonia3controller@index1');
	Route::get('/he_ammonia3','rbiammonia3controller@index2');
	Route::get('/pv_ammonia3','rbiammonia3controller@index3');

	Route::resource('/rbiammonia3pv', 'rbiammonia3pvcontroller');
	Route::POST('/rbiammonia3pv/create','rbiammonia3pvcontroller@create');
	Route::get('/rbiammonia3pv/{id}/edit','rbiammonia3pvcontroller@edit');
	Route::POST('/rbiammonia3pv/{id}/update','rbiammonia3pvcontroller@update');
	Route::get('/rbiammonia3pv/{id}/delete','rbiammonia3pvcontroller@delete');
	Route::get('/rbiammonia3pv/{id}/detail','rbiammonia3pvcontroller@detail');

	Route::resource('/rbiammonia3he', 'rbiammonia3hecontroller');
	Route::POST('/rbiammonia3he/create','rbiammonia3hecontroller@create');
	Route::get('/rbiammonia3he/{id}/edit','rbiammonia3hecontroller@edit');
	Route::POST('/rbiammonia3he/{id}/update','rbiammonia3hecontroller@update');
	Route::get('/rbiammonia3he/{id}/delete','rbiammonia3hecontroller@delete');
	Route::get('/rbiammonia3he/{id}/detail','rbiammonia3hecontroller@detail');

	Route::resource('/rbiurea3', 'rbiurea3controller');
	Route::get('/rbiurea3','rbiurea3controller@index');
	Route::POST('/rbiurea3/create','rbiurea3controller@create');
	Route::get('/rbiurea3/{id}/edit','rbiurea3controller@edit');
	Route::POST('/rbiurea3/{id}/update','rbiurea3controller@update');
	Route::get('/rbiurea3/{id}/delete','rbiurea3controller@delete');
	Route::get('/rbiurea3/{id}/detail','rbiurea3controller@detail');
	Route::get('/prd_urea3','rbiurea3controller@index1');
	Route::get('/pv_urea3','rbiurea3controller@index2');
	Route::get('/ast_urea3','rbiurea3controller@index3');
	Route::get('/he_urea3','rbiurea3controller@index4');

	Route::resource('/rbiurea3pv', 'rbiurea3pvcontroller');
	Route::POST('/rbiurea3pv/create','rbiurea3pvcontroller@create');
	Route::get('/rbiurea3pv/{id}/edit','rbiurea3pvcontroller@edit');
	Route::POST('/rbiurea3pv/{id}/update','rbiurea3pvcontroller@update');
	Route::get('/rbiurea3pv/{id}/delete','rbiurea3pvcontroller@delete');
	Route::get('/rbiurea3pv/{id}/detail','rbiurea3pvcontroller@detail');

	Route::resource('/rbiurea3tank', 'rbiurea3tankcontroller');
	Route::POST('/rbiurea3tank/create','rbiurea3tankcontroller@create');
	Route::get('/rbiurea3tank/{id}/edit','rbiurea3tankcontroller@edit');
	Route::POST('/rbiurea3tank/{id}/update','rbiurea3tankcontroller@update');
	Route::get('/rbiurea3tank/{id}/delete','rbiurea3tankcontroller@delete');
	Route::get('/rbiurea3tank/{id}/detail','rbiurea3tankcontroller@detail');

	Route::resource('/rbiurea3he', 'rbiurea3hecontroller');
	Route::POST('/rbiurea3he/create','rbiurea3hecontroller@create');
	Route::get('/rbiurea3he/{id}/edit','rbiurea3hecontroller@edit');
	Route::POST('/rbiurea3he/{id}/update','rbiurea3hecontroller@update');
	Route::get('/rbiurea3he/{id}/delete','rbiurea3hecontroller@delete');
	Route::get('/rbiurea3he/{id}/detail','rbiurea3hecontroller@detail');

	Route::resource('/rbiutilitas3', 'rbiutilitas3controller');
	Route::get('/rbiutilitas3','rbiutilitas3controller@index');
	Route::POST('/rbiutilitas3/create','rbiutilitas3controller@create');
	Route::get('/rbiutilitas3/{id}/edit','rbiutilitas3controller@edit');
	Route::POST('/rbiutilitas3/{id}/update','rbiutilitas3controller@update');
	Route::get('/rbiutilitas3/{id}/delete','rbiutilitas3controller@delete');
	Route::get('/rbiutilitas3/{id}/detail','rbiutilitas3controller@detail');
	Route::get('/pv_utilitas3','rbiutilitas3controller@index1');
	Route::get('/ast_utilitas3','rbiutilitas3controller@index2');
	Route::get('/he_utilitas3','rbiutilitas3controller@index3');

	Route::resource('/rbiutilitas3tank', 'rbiutilitas3tankcontroller');
	Route::POST('/rbiutilitas3tank/create','rbiutilitas3tankcontroller@create');
	Route::get('/rbiutilitas3tank/{id}/edit','rbiutilitas3tankcontroller@edit');
	Route::POST('/rbiutilitas3tank/{id}/update','rbiutilitas3tankcontroller@update');
	Route::get('/rbiutilitas3tank/{id}/delete','rbiutilitas3tankcontroller@delete');
	Route::get('/rbiutilitas3tank/{id}/detail','rbiutilitas3tankcontroller@detail');

	Route::resource('/rbiutilitas3he', 'rbiutilitas3hecontroller');
	Route::POST('/rbiutilitas3he/create','rbiutilitas3hecontroller@create');
	Route::get('/rbiutilitas3he/{id}/edit','rbiutilitas3hecontroller@edit');
	Route::POST('/rbiutilitas3he/{id}/update','rbiutilitas3hecontroller@update');
	Route::get('/rbiutilitas3he/{id}/delete','rbiutilitas3hecontroller@delete');
	Route::get('/rbiutilitas3he/{id}/detail','rbiutilitas3hecontroller@detail');

	Route::resource('/rbiammonia4', 'rbiammonia4controller');
	Route::get('/rbiammonia4','rbiammonia4controller@index');
	Route::POST('/rbiammonia4/create','rbiammonia4controller@create');
	Route::get('/rbiammonia4/{id}/edit','rbiammonia4controller@edit');
	Route::POST('/rbiammonia4/{id}/update','rbiammonia4controller@update');
	Route::get('/rbiammonia4/{id}/delete','rbiammonia4controller@delete');
	Route::get('/rbiammonia4/{id}/detail','rbiammonia4controller@detail');
	Route::get('/prd_ammonia4','rbiammonia4controller@index1');
	Route::get('/he_ammonia4','rbiammonia4controller@index2');
	Route::get('/pv_ammonia4','rbiammonia4controller@index3');

	Route::resource('/rbiammonia4pv', 'rbiammonia4pvcontroller');
	Route::POST('/rbiammonia4pv/create','rbiammonia4pvcontroller@create');
	Route::get('/rbiammonia4pv/{id}/edit','rbiammonia4pvcontroller@edit');
	Route::POST('/rbiammonia4pv/{id}/update','rbiammonia4pvcontroller@update');
	Route::get('/rbiammonia4pv/{id}/delete','rbiammonia4pvcontroller@delete');
	Route::get('/rbiammonia4pv/{id}/detail','rbiammonia4pvcontroller@detail');

	Route::resource('/rbiammonia4he', 'rbiammonia4hecontroller');
	Route::POST('/rbiammonia4he/create','rbiammonia4hecontroller@create');
	Route::get('/rbiammonia4he/{id}/edit','rbiammonia4hecontroller@edit');
	Route::POST('/rbiammonia4he/{id}/update','rbiammonia4hecontroller@update');
	Route::get('/rbiammonia4he/{id}/delete','rbiammonia4hecontroller@delete');
	Route::get('/rbiammonia4he/{id}/detail','rbiammonia4hecontroller@detail');

	Route::resource('/rbiurea4', 'rbiurea4controller');
	Route::get('/rbiurea4','rbiurea4controller@index');
	Route::POST('/rbiurea4/create','rbiurea4controller@create');
	Route::get('/rbiurea4/{id}/edit','rbiurea4controller@edit');
	Route::POST('/rbiurea4/{id}/update','rbiurea4controller@update');
	Route::get('/rbiurea4/{id}/delete','rbiurea4controller@delete');
	Route::get('/rbiurea4/{id}/detail','rbiurea4controller@detail');
	Route::get('/prd_urea4','rbiurea4controller@index1');
	Route::get('/pv_urea4','rbiurea4controller@index2');
	Route::get('/ast_urea4','rbiurea4controller@index3');
	Route::get('/he_urea4','rbiurea4controller@index4');

	Route::resource('/rbiurea4pv', 'rbiurea4pvcontroller');
	Route::POST('/rbiurea4pv/create','rbiurea4pvcontroller@create');
	Route::get('/rbiurea4pv/{id}/edit','rbiurea4pvcontroller@edit');
	Route::POST('/rbiurea4pv/{id}/update','rbiurea4pvcontroller@update');
	Route::get('/rbiurea4pv/{id}/delete','rbiurea4pvcontroller@delete');
	Route::get('/rbiurea4pv/{id}/detail','rbiurea4pvcontroller@detail');

	Route::resource('/rbiurea4tank', 'rbiurea4tankcontroller');
	Route::POST('/rbiurea4tank/create','rbiurea4tankcontroller@create');
	Route::get('/rbiurea4tank/{id}/edit','rbiurea4tankcontroller@edit');
	Route::POST('/rbiurea4tank/{id}/update','rbiurea4tankcontroller@update');
	Route::get('/rbiurea4tank/{id}/delete','rbiurea4tankcontroller@delete');
	Route::get('/rbiurea4tank/{id}/detail','rbiurea4tankcontroller@detail');

	Route::resource('/rbiurea4he', 'rbiurea4hecontroller');
	Route::POST('/rbiurea4he/create','rbiurea4hecontroller@create');
	Route::get('/rbiurea4he/{id}/edit','rbiurea4hecontroller@edit');
	Route::POST('/rbiurea4he/{id}/update','rbiurea4hecontroller@update');
	Route::get('/rbiurea4he/{id}/delete','rbiurea4hecontroller@delete');
	Route::get('/rbiurea4he/{id}/detail','rbiurea4hecontroller@detail');

	Route::resource('/rbiutilitas4', 'rbiutilitas4controller');
	Route::get('/rbiutilitas4','rbiutilitas4controller@index');
	Route::POST('/rbiutilitas4/create','rbiutilitas4controller@create');
	Route::get('/rbiutilitas4/{id}/edit','rbiutilitas4controller@edit');
	Route::POST('/rbiutilitas4/{id}/update','rbiutilitas4controller@update');
	Route::get('/rbiutilitas4/{id}/delete','rbiutilitas4controller@delete');
	Route::get('/rbiutilitas4/{id}/detail','rbiutilitas4controller@detail');
	Route::get('/pv_utilitas4','rbiutilitas4controller@index1');
	Route::get('/ast_utilitas4','rbiutilitas4controller@index2');
	Route::get('/he_utilitas4','rbiutilitas4controller@index3');

	Route::resource('/rbiutilitas4tank', 'rbiutilitas4tankcontroller');
	Route::POST('/rbiutilitas4tank/create','rbiutilitas4tankcontroller@create');
	Route::get('/rbiutilitas4tank/{id}/edit','rbiutilitas4tankcontroller@edit');
	Route::POST('/rbiutilitas4tank/{id}/update','rbiutilitas4tankcontroller@update');
	Route::get('/rbiutilitas4tank/{id}/delete','rbiutilitas4tankcontroller@delete');
	Route::get('/rbiutilitas4tank/{id}/detail','rbiutilitas4tankcontroller@detail');

	Route::resource('/rbiutilitas4he', 'rbiutilitas4hecontroller');
	Route::POST('/rbiutilitas4he/create','rbiutilitas4hecontroller@create');
	Route::get('/rbiutilitas4he/{id}/edit','rbiutilitas4hecontroller@edit');
	Route::POST('/rbiutilitas4he/{id}/update','rbiutilitas4hecontroller@update');
	Route::get('/rbiutilitas4he/{id}/delete','rbiutilitas4hecontroller@delete');
	Route::get('/rbiutilitas4he/{id}/detail','rbiutilitas4hecontroller@detail');

	Route::resource('/rbinpk', 'rbinpkcontroller');
	Route::get('/rbinpk','rbinpkcontroller@index');
	Route::POST('/rbinpk/create','rbinpkcontroller@create');
	Route::get('/rbinpk/{id}/edit','rbinpkcontroller@edit');
	Route::POST('/rbinpk/{id}/update','rbinpkcontroller@update');
	Route::get('/rbinpk/{id}/delete','rbinpkcontroller@delete');
	Route::get('/rbinpk/{id}/detail','rbinpkcontroller@detail');
	Route::get('/prd_npk','rbinpkcontroller@index1');
	Route::get('/pv_npk','rbinpkcontroller@index2');
	Route::get('/ast_npk','rbinpkcontroller@index3');
	Route::get('/he_npk','rbinpkcontroller@index4');

	Route::resource('/rbinpkpv', 'rbinpkpvcontroller');
	Route::POST('/rbinpkpv/create','rbinpkpvcontroller@create');
	Route::get('/rbinpkpv/{id}/edit','rbinpkpvcontroller@edit');
	Route::POST('/rbinpkpv/{id}/update','rbinpkpvcontroller@update');
	Route::get('/rbinpkpv/{id}/delete','rbinpkpvcontroller@delete');
	Route::get('/rbinpkpv/{id}/detail','rbinpkpvcontroller@detail');

	Route::resource('/rbinpktank', 'rbinpktankcontroller');
	Route::POST('/rbinpktank/create','rbinpktankcontroller@create');
	Route::get('/rbinpktank/{id}/edit','rbinpktankcontroller@edit');
	Route::POST('/rbinpktank/{id}/update','rbinpktankcontroller@update');
	Route::get('/rbinpktank/{id}/delete','rbinpktankcontroller@delete');
	Route::get('/rbinpktank/{id}/detail','rbinpktankcontroller@detail');

	Route::resource('/rbinpkhe', 'rbinpkhecontroller');
	Route::POST('/rbinpkhe/create','rbinpkhecontroller@create');
	Route::get('/rbinpkhe/{id}/edit','rbinpkhecontroller@edit');
	Route::POST('/rbinpkhe/{id}/update','rbinpkhecontroller@update');
	Route::get('/rbinpkhe/{id}/delete','rbinpkhecontroller@delete');
	Route::get('/rbinpkhe/{id}/detail','rbinpkhecontroller@detail');

	Route::resource('/rbistgbbjetty', 'rbistgbbjettycontroller');
	Route::get('/rbistgbbjetty','rbistgbbjettycontroller@index');
	Route::POST('/rbistgbbjetty/create','rbistgbbjettycontroller@create');
	Route::get('/rbistgbbjetty/{id}/edit','rbistgbbjettycontroller@edit');
	Route::POST('/rbistgbbjetty/{id}/update','rbistgbbjettycontroller@update');
	Route::get('/rbistgbbjetty/{id}/delete','rbistgbbjettycontroller@delete');
	Route::get('/rbistgbbjetty/{id}/detail','rbistgbbjettycontroller@detail');
	Route::get('/prd_stgbbjetty','rbistgbbjettycontroller@index1');
	Route::get('/pv_stgbbjetty','rbistgbbjettycontroller@index2');
	Route::get('/ast_stgbbjetty','rbistgbbjettycontroller@index3');
	Route::get('/he_stgbbjetty','rbistgbbjettycontroller@index4');

	Route::resource('/rbistgbbjettypv', 'rbistgbbjettypvcontroller');
	Route::POST('/rbistgbbjettypv/create','rbistgbbjettypvcontroller@create');
	Route::get('/rbistgbbjettypv/{id}/edit','rbistgbbjettypvcontroller@edit');
	Route::POST('/rbistgbbjettypv/{id}/update','rbistgbbjettypvcontroller@update');
	Route::get('/rbistgbbjettypv/{id}/delete','rbistgbbjettypvcontroller@delete');
	Route::get('/rbistgbbjettypv/{id}/detail','rbistgbbjettypvcontroller@detail');

	Route::resource('/rbistgbbjettytank', 'rbistgbbjettytankcontroller');
	Route::POST('/rbistgbbjettytank/create','rbistgbbjettytankcontroller@create');
	Route::get('/rbistgbbjettytank/{id}/edit','rbistgbbjettytankcontroller@edit');
	Route::POST('/rbistgbbjettytank/{id}/update','rbistgbbjettytankcontroller@update');
	Route::get('/rbistgbbjettytank/{id}/delete','rbistgbbjettytankcontroller@delete');
	Route::get('/rbistgbbjettytank/{id}/detail','rbistgbbjettytankcontroller@detail');

	Route::resource('/rbistgbbjettyhe', 'rbistgbbjettyhecontroller');
	Route::POST('/rbistgbbjettyhe/create','rbistgbbjettyhecontroller@create');
	Route::get('/rbistgbbjettyhe/{id}/edit','rbistgbbjettyhecontroller@edit');
	Route::POST('/rbistgbbjettyhe/{id}/update','rbistgbbjettyhecontroller@update');
	Route::get('/rbistgbbjettyhe/{id}/delete','rbistgbbjettyhecontroller@delete');
	Route::get('/rbistgbbjettyhe/{id}/detail','rbistgbbjettyhecontroller@detail');

	Route::resource('/hcammonia1b', 'hcammonia1bcontroller');
	Route::get('/hcammonia1b','hcammonia1bcontroller@index');
	Route::POST('/hcammonia1b/create','hcammonia1bcontroller@create');
	Route::get('/hcammonia1b/{id}/edit','hcammonia1bcontroller@edit');
	Route::POST('/hcammonia1b/{id}/update','hcammonia1bcontroller@update');
	Route::get('/hcammonia1b/{id}/delete','hcammonia1bcontroller@delete');
	Route::resource('/hcurea1b', 'hcurea1bcontroller');
	Route::get('/hcurea1b','hcurea1bcontroller@index');
	Route::POST('/hcurea1b/create','hcurea1bcontroller@create');
	Route::get('/hcurea1b/{id}/edit','hcurea1bcontroller@edit');
	Route::POST('/hcurea1b/{id}/update','hcurea1bcontroller@update');
	Route::get('/hcurea1b/{id}/delete','hcurea1bcontroller@delete');
	Route::resource('/hcutilitas1b', 'hcutilitas1bcontroller');
	Route::get('/hcutilitas1b','hcutilitas1bcontroller@index');
	Route::POST('/hcutilitas1b/create','hcutilitas1bcontroller@create');
	Route::get('/hcutilitas1b/{id}/edit','hcutilitas1bcontroller@edit');
	Route::POST('/hcutilitas1b/{id}/update','hcutilitas1bcontroller@update');
	Route::get('/hcutilitas1b/{id}/delete','hcutilitas1bcontroller@delete');

	Route::resource('/hcammonia2b', 'hcammonia2bcontroller');
	Route::get('/hcammonia2b','hcammonia2bcontroller@index');
	Route::POST('/hcammonia2b/create','hcammonia2bcontroller@create');
	Route::get('/hcammonia2b/{id}/edit','hcammonia2bcontroller@edit');
	Route::POST('/hcammonia2b/{id}/update','hcammonia2bcontroller@update');
	Route::get('/hcammonia2b/{id}/delete','hcammonia2bcontroller@delete');
	Route::resource('/hcurea2b', 'hcurea2bcontroller');
	Route::get('/hcurea2b','hcurea2bcontroller@index');
	Route::POST('/hcurea2b/create','hcurea2bcontroller@create');
	Route::get('/hcurea2b/{id}/edit','hcurea2bcontroller@edit');
	Route::POST('/hcurea2b/{id}/update','hcurea2bcontroller@update');
	Route::get('/hcurea2b/{id}/delete','hcurea2bcontroller@delete');
	Route::resource('/hcutilitas2b', 'hcutilitas2bcontroller');
	Route::get('/hcutilitas2b','hcutilitas2bcontroller@index');
	Route::POST('/hcutilitas2b/create','hcutilitas2bcontroller@create');
	Route::get('/hcutilitas2b/{id}/edit','hcutilitas2bcontroller@edit');
	Route::POST('/hcutilitas2b/{id}/update','hcutilitas2bcontroller@update');
	Route::get('/hcutilitas2b/{id}/delete','hcutilitas2bcontroller@delete');

	Route::resource('/hcammonia3', 'hcammonia3controller');
	Route::get('/hcammonia3','hcammonia3controller@index');
	Route::POST('/hcammonia3/create','hcammonia3controller@create');
	Route::get('/hcammonia3/{id}/edit','hcammonia3controller@edit');
	Route::POST('/hcammonia3/{id}/update','hcammonia3controller@update');
	Route::get('/hcammonia3/{id}/delete','hcammonia3controller@delete');
	Route::resource('/hcurea3', 'hcurea3controller');
	Route::get('/hcurea3','hcurea3controller@index');
	Route::POST('/hcurea3/create','hcurea3controller@create');
	Route::get('/hcurea3/{id}/edit','hcurea3controller@edit');
	Route::POST('/hcurea3/{id}/update','hcurea3controller@update');
	Route::get('/hcurea3/{id}/delete','hcurea3controller@delete');
	Route::resource('/hcutilitas3', 'hcutilitas3controller');
	Route::get('/hcutilitas3','hcutilitas3controller@index');
	Route::POST('/hcutilitas3/create','hcutilitas3controller@create');
	Route::get('/hcutilitas3/{id}/edit','hcutilitas3controller@edit');
	Route::POST('/hcutilitas3/{id}/update','hcutilitas3controller@update');
	Route::get('/hcutilitas3/{id}/delete','hcutilitas3controller@delete');

	Route::resource('/hcammonia4', 'hcammonia4controller');
	Route::get('/hcammonia4','hcammonia4controller@index');
	Route::POST('/hcammonia4/create','hcammonia4controller@create');
	Route::get('/hcammonia4/{id}/edit','hcammonia4controller@edit');
	Route::POST('/hcammonia4/{id}/update','hcammonia4controller@update');
	Route::get('/hcammonia4/{id}/delete','hcammonia4controller@delete');
	Route::resource('/hcurea4', 'hcurea4controller');
	Route::get('/hcurea4','hcurea4controller@index');
	Route::POST('/hcurea4/create','hcurea4controller@create');
	Route::get('/hcurea4/{id}/edit','hcurea4controller@edit');
	Route::POST('/hcurea4/{id}/update','hcurea4controller@update');
	Route::get('/hcurea4/{id}/delete','hcurea4controller@delete');
	Route::resource('/hcutilitas4', 'hcutilitas4controller');
	Route::get('/hcutilitas4','hcutilitas4controller@index');
	Route::POST('/hcutilitas4/create','hcutilitas4controller@create');
	Route::get('/hcutilitas4/{id}/edit','hcutilitas4controller@edit');
	Route::POST('/hcutilitas4/{id}/update','hcutilitas4controller@update');
	Route::get('/hcutilitas4/{id}/delete','hcutilitas4controller@delete');

	Route::resource('/hcnpk', 'hcnpkcontroller');
	Route::get('/hcnpk','hcnpkcontroller@index');
	Route::POST('/hcnpk/create','hcnpkcontroller@create');
	Route::get('/hcnpk/{id}/edit','hcnpkcontroller@edit');
	Route::POST('/hcnpk/{id}/update','hcnpkcontroller@update');
	Route::get('/hcnpk/{id}/delete','hcnpkcontroller@delete');
	Route::resource('/hcstgbbjetty', 'hcstgbbjettycontroller');
	Route::get('/hcstgbbjetty','hcstgbbjettycontroller@index');
	Route::POST('/hcstgbbjetty/create','hcstgbbjettycontroller@create');
	Route::get('/hcstgbbjetty/{id}/edit','hcstgbbjettycontroller@edit');
	Route::POST('/hcstgbbjetty/{id}/update','hcstgbbjettycontroller@update');
	Route::get('/hcstgbbjetty/{id}/delete','hcstgbbjettycontroller@delete');

	Route::resource('/itpmammonia1b', 'itpmammonia1bcontroller');
	Route::get('/itpmammonia1b','itpmammonia1bcontroller@index');
	Route::resource('/itpmurea1b', 'itpmurea1bcontroller');
	Route::get('/itpmurea1b','itpmurea1bcontroller@index');
	Route::resource('/itpmutilitas1b', 'itpmutilitas1bcontroller');
	Route::get('/itpmutilitas1b','itpmutilitas1bcontroller@index');
	Route::resource('/itpmammonia2b', 'itpmammonia2bcontroller');
	Route::get('/itpmammonia2b','itpmammonia2bcontroller@index');
	Route::resource('/itpmurea2b', 'itpmurea2bcontroller');
	Route::get('/itpmurea2b','itpmurea2bcontroller@index');
	Route::resource('/itpmutilitas2b', 'itpmutilitas2bcontroller');
	Route::get('/itpmutilitas2b','itpmutilitas2bcontroller@index');
	Route::resource('/itpmammonia3', 'itpmammonia3controller');
	Route::get('/itpmammonia3','itpmammonia3controller@index');
	Route::resource('/itpmurea3', 'itpmurea3controller');
	Route::get('/itpmurea3','itpmurea3controller@index');
	Route::resource('/itpmutilitas3', 'itpmutilitas3controller');
	Route::get('/itpmutilitas3','itpmutilitas3controller@index');
	Route::resource('/itpmammonia4', 'itpmammonia4controller');
	Route::get('/itpmammonia4','itpmammonia4controller@index');
	Route::resource('/itpmurea4', 'itpmurea4controller');
	Route::get('/itpmurea4','itpmurea4controller@index');
	Route::resource('/itpmutilitas4', 'itpmutilitas4controller');
	Route::get('/itpmutilitas4','itpmutilitas4controller@index');
	Route::resource('/itpmnpk', 'itpmnpkcontroller');
	Route::get('/itpmnpk','itpmnpkcontroller@index');
	Route::resource('/itpmstgbbjetty', 'itpmstgbbjettycontroller');
	Route::get('/itpmstgbbjetty','itpmstgbbjettycontroller@index');

	Route::resource('/usermanage', 'usermanagecontroller');
	Route::get('/usermanage','usermanagecontroller@index');
	Route::POST('/usermanage/create','usermanagecontroller@create');
	Route::resource('/employee_data','employeecontroller');
	Route::get('/employee_data','employeecontroller@index');

	Route::resource('/rekomammonia1b', 'rekomammonia1bcontroller');
	Route::get('/rekomammonia1b','rekomammonia1bcontroller@index');
	Route::POST('/rekomammonia1b/create','rekomammonia1bcontroller@create');
	Route::get('/rekomammonia1b/{id}/edit','rekomammonia1bcontroller@edit');
	Route::POST('/rekomammonia1b/{id}/update','rekomammonia1bcontroller@update');
	Route::get('/rekomammonia1b/{id}/delete','rekomammonia1bcontroller@delete');
	Route::resource('/rekomurea1b', 'rekomurea1bcontroller');
	Route::get('/rekomurea1b','rekomurea1bcontroller@index');
	Route::POST('/rekomurea1b/create','rekomurea1bcontroller@create');
	Route::get('/rekomurea1b/{id}/edit','rekomurea1bcontroller@edit');
	Route::POST('/rekomurea1b/{id}/update','rekomurea1bcontroller@update');
	Route::get('/rekomurea1b/{id}/delete','rekomurea1bcontroller@delete');
	Route::resource('/rekomutilitas1b', 'rekomutilitas1bcontroller');
	Route::get('/rekomutilitas1b','rekomutilitas1bcontroller@index');
	Route::POST('/rekomutilitas1b/create','rekomutilitas1bcontroller@create');
	Route::get('/rekomutilitas1b/{id}/edit','rekomutilitas1bcontroller@edit');
	Route::POST('/rekomutilitas1b/{id}/update','rekomutilitas1bcontroller@update');
	Route::get('/rekomutilitas1b/{id}/delete','rekomutilitas1bcontroller@delete');

	Route::resource('/rekomammonia2b', 'rekomammonia2bcontroller');
	Route::get('/rekomammonia2b','rekomammonia2bcontroller@index');
	Route::POST('/rekomammonia2b/create','rekomammonia2bcontroller@create');
	Route::get('/rekomammonia2b/{id}/edit','rekomammonia2bcontroller@edit');
	Route::POST('/rekomammonia2b/{id}/update','rekomammonia2bcontroller@update');
	Route::get('/rekomammonia2b/{id}/delete','rekomammonia2bcontroller@delete');
	Route::resource('/rekomurea2b', 'rekomurea2bcontroller');
	Route::get('/rekomurea2b','rekomurea2bcontroller@index');
	Route::POST('/rekomurea2b/create','rekomurea2bcontroller@create');
	Route::get('/rekomurea2b/{id}/edit','rekomurea2bcontroller@edit');
	Route::POST('/rekomurea2b/{id}/update','rekomurea2bcontroller@update');
	Route::get('/rekomurea2b/{id}/delete','rekomurea2bcontroller@delete');
	Route::resource('/rekomutilitas2b', 'rekomutilitas2bcontroller');
	Route::get('/rekomutilitas2b','rekomutilitas2bcontroller@index');
	Route::POST('/rekomutilitas2b/create','rekomutilitas2bcontroller@create');
	Route::get('/rekomutilitas2b/{id}/edit','rekomutilitas2bcontroller@edit');
	Route::POST('/rekomutilitas2b/{id}/update','rekomutilitas2bcontroller@update');
	Route::get('/rekomutilitas2b/{id}/delete','rekomutilitas2bcontroller@delete');

	Route::resource('/rekomammonia3', 'rekomammonia3controller');
	Route::get('/rekomammonia3','rekomammonia3controller@index');
	Route::POST('/rekomammonia3/create','rekomammonia3controller@create');
	Route::get('/rekomammonia3/{id}/edit','rekomammonia3controller@edit');
	Route::POST('/rekomammonia3/{id}/update','rekomammonia3controller@update');
	Route::get('/rekomammonia3/{id}/delete','rekomammonia3controller@delete');
	Route::resource('/rekomurea3', 'rekomurea3controller');
	Route::get('/rekomurea3','rekomurea3controller@index');
	Route::POST('/rekomurea3/create','rekomurea3controller@create');
	Route::get('/rekomurea3/{id}/edit','rekomurea3controller@edit');
	Route::POST('/rekomurea3/{id}/update','rekomurea3controller@update');
	Route::get('/rekomurea3/{id}/delete','rekomurea3controller@delete');
	Route::resource('/rekomutilitas3', 'rekomutilitas3controller');
	Route::get('/rekomutilitas3','rekomutilitas3controller@index');
	Route::POST('/rekomutilitas3/create','rekomutilitas3controller@create');
	Route::get('/rekomutilitas3/{id}/edit','rekomutilitas3controller@edit');
	Route::POST('/rekomutilitas3/{id}/update','rekomutilitas3controller@update');
	Route::get('/rekomutilitas3/{id}/delete','rekomutilitas3controller@delete');

	Route::resource('/rekomammonia4', 'rekomammonia4controller');
	Route::get('/rekomammonia4','rekomammonia4controller@index');
	Route::POST('/rekomammonia4/create','rekomammonia4controller@create');
	Route::get('/rekomammonia4/{id}/edit','rekomammonia4controller@edit');
	Route::POST('/rekomammonia4/{id}/update','rekomammonia4controller@update');
	Route::get('/rekomammonia4/{id}/delete','rekomammonia4controller@delete');
	Route::resource('/rekomurea4', 'rekomurea4controller');
	Route::get('/rekomurea4','rekomurea4controller@index');
	Route::POST('/rekomurea4/create','rekomurea4controller@create');
	Route::get('/rekomurea4/{id}/edit','rekomurea4controller@edit');
	Route::POST('/rekomurea4/{id}/update','rekomurea4controller@update');
	Route::get('/rekomurea4/{id}/delete','rekomurea4controller@delete');
	Route::resource('/rekomutilitas4', 'rekomutilitas4controller');
	Route::get('/rekomutilitas4','rekomutilitas4controller@index');
	Route::POST('/rekomutilitas4/create','rekomutilitas4controller@create');
	Route::get('/rekomutilitas4/{id}/edit','rekomutilitas4controller@edit');
	Route::POST('/rekomutilitas4/{id}/update','rekomutilitas4controller@update');
	Route::get('/rekomutilitas4/{id}/delete','rekomutilitas4controller@delete');

	Route::resource('/rekomnpk', 'rekomnpkcontroller');
	Route::get('/rekomnpk','rekomnpkcontroller@index');
	Route::POST('/rekomnpk/create','rekomnpkcontroller@create');
	Route::get('/rekomnpk/{id}/edit','rekomnpkcontroller@edit');
	Route::POST('/rekomnpk/{id}/update','rekomnpkcontroller@update');
	Route::get('/rekomnpk/{id}/delete','rekomnpkcontroller@delete');
	Route::resource('/rekomstgbbjetty', 'rekomstgbbjettycontroller');
	Route::get('/rekomstgbbjetty','rekomstgbbjettycontroller@index');
	Route::POST('/rekomstgbbjetty/create','rekomstgbbjettycontroller@create');
	Route::get('/rekomstgbbjetty/{id}/edit','rekomstgbbjettycontroller@edit');
	Route::POST('/rekomstgbbjetty/{id}/update','rekomstgbbjettycontroller@update');
	Route::get('/rekomstgbbjetty/{id}/delete','rekomstgbbjettycontroller@delete');
});
	